name: stride
description: Task management tool that synchronizes with Git.
publish_to: "none"
homepage: https://github.com/stride-tasks/stride
repository: https://github.com/stride-tasks/stride

version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stride_flutter_bridge:
    path: rust_builder
  flutter_rust_bridge: ^2.3.0
  uuid: ^4.5.0
  path: ^1.9.0
  path_provider: ^2.1.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  font_awesome_flutter: ^10.7.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.2
  freezed: ^2.5.2
  build_runner: ^2.4.12

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/logo.png"
  android: true
  adaptive_icon_background: "#282828"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter_rust_bridge:
  rust_input: crate::api
  rust_root: ../crates/flutter_bridge/
  dart_output: lib/bridge
  web: false
  # TODO: Maybe remove some of the lint ignores, and run `dart fix --apply` or wait for
  # https://github.com/fzyzcjy/flutter_rust_bridge/pull/2182
  dart_preamble: |
    // ignore_for_file: require_trailing_commas
    // ignore_for_file: always_use_package_imports
    // ignore_for_file: directives_ordering
    // ignore_for_file: sort_unnamed_constructors_first
    // ignore_for_file: avoid_unused_constructor_parameters
    // ignore_for_file: avoid_dynamic_calls
    // ignore_for_file: avoid_equals_and_hash_code_on_mutable_classes
    // ignore_for_file: prefer_final_locals
    // ignore_for_file: argument_type_not_assignable
    // ignore_for_file: inference_failure_on_instance_creation
    // ignore_for_file: prefer_single_quotes
    // ignore_for_file: avoid_redundant_argument_values
    // ignore_for_file: noop_primitive_operations
    // ignore_for_file: prefer_const_constructors
    // ignore_for_file: prefer_is_empty
    // ignore_for_file: unnecessary_parenthesis
